import year2023.day10.Maze;
import year2023.day16.Cave;
import year2023.day17.HeatLoss;
import year2023.day18.Lagoon;
import year2023.day19.Aplenty;
import year2023.day20.Pulses;
import year2023.day21.Steps;

public class Main {

    public static void main(String[] args) {
//        System.out.println(new Calories().p2());
//        System.out.println(new RPS().p1());
//        System.out.println(new RPS().p2());
//        System.out.println(new Cleaning().findCompleteOverlaps());
//        System.out.println(new Crates().execute(false));
//        System.out.println(new Signal().findUniqueCharactersIndex(14));
//        System.out.println(new FileSystem().populate());
//        Forest forest = new Forest();
//        System.out.println(forest.findVisible());
//        System.out.println(forest.calculateMaxScenicValue());
//        System.out.println(new Rope(1).execute());
//        CPU cpu = new CPU(40);
//        System.out.println(cpu.execute());
//        cpu.draw();
//        Jungle jungle = new Jungle();
//        Calibration calibration = new Calibration();
//        System.out.println(calibration.p1());
//        Cubes cubes = new Cubes();
//        System.out.println(cubes.valid());
//        System.out.println(cubes.minimum());
//        Engine engine = new Engine();
//        engine.findAdjacentPoints(Engine::isGear);
//        engine.execute();
//        System.out.println(engine.getAdjacentSum());
//        System.out.println(engine.getGearRatio());
//        Lottery lottery = new Lottery();
//        System.out.println(lottery.calculateScore().intValue());
//        System.out.println(lottery.calculateCards());
//        Garden garden = new Garden();
//        System.out.println("RESULT - " + garden.calculate());
//        Race race = new Race();
//        System.out.println(race.run());
//        System.out.println(race.finalRun());
//        Poker poker = new Poker();
//        System.out.println(poker.run("AKQJT98765432", false));
//        System.out.println(poker.run("AKQT98765432J", true));
//        Desert desert = new Desert();
//        System.out.println(desert.traverse("AAA", "ZZZ"));
//        System.out.println(desert.traverse("A", "Z"));
//        Universe universe = new Universe();
//        System.out.println(universe.findShortestPaths(2));
//        System.out.println(universe.findShortestPaths(1000000));
//        Springs springs = new Springs();
//        System.out.println(springs.process(0));
//        System.out.println(springs.process(4));
//        Volcano mirrors = new Volcano();
//        System.out.println(mirrors.calculate(Volcano.Result.TRUE));
//        SimpleDish simpleDish = new SimpleDish();
//        System.out.println(simpleDish.calculateWeight());
//        Dish dish = new Dish();
//        System.out.println(dish.calculateWeight(1000000000));
//        Library library = new Library();
//        System.out.println(library.sumHashes());
//        System.out.println(library.execute());
//        Cave cave = new Cave();
//        System.out.println(cave.energized());
//        System.out.println(cave.findMax());
//        Oasis oasis = new Oasis();
//        System.out.println(oasis.calculate(true));
//        Lagoon lagoon = new Lagoon();
//        System.out.println(lagoon.dugSimple());
//        System.out.println(lagoon.dugHex());
//        Pulses pulses = new Pulses();
//        pulses.run();
//        System.out.println(pulses.getTotal());
//        System.out.println(pulses.getMinimumForRX());
//        Aplenty aplenty = new Aplenty();
//        System.out.println(aplenty.accepted());
//        System.out.println(aplenty.calc());
//        Maze maze = new Maze();
//        System.out.println(maze.getSteps());
//        System.out.println(maze.getArea());
//        HeatLoss heatLoss = new HeatLoss();
//        System.out.println(heatLoss.minimizeHeatLoss());
        Steps steps = new Steps();
        System.out.println(steps.move(64));
        System.out.println(steps.numberOfPossibleDestinations(26501365));
    }
}
